export const actionTypes = {
  Login: "[Login] Action",
  Logout: "[Logout] Action",
  Register: "[Register] Action",
  UserRequested: "[Request User] Action",
  UserLoaded: "[Load User] Auth API",
  facilty: "FACILITY_SELECTED",
  damageCodeList: "DAMAGE_CODE_LIST",
  facilityList: "FACILITY_LIST",
  yardCraneList: "YARD_CRANE_LIST",
  blockList: "BLOCK_LIST",
  yardCrane: "YARD_CRANE",
  yardOperation: "YARD_OPERATIONS",
  yardJobOption: "YARD_JOB_OPTIONS",
  gateInOperationOpations: "GATE_IN_OPERAATION_OPTIONS",
  groundContainer: "GROUND_CONTAINER",
};
